#!/bin/sh
pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 3
bspc config focused_border_color "#89b4fa"
bspc config normal_border_color "#6c7086"
bspc config active_border_color "#6c7086"
bspc config window_gap 2
bspc config split_ratio 0.5
bspc config focus_follows_pointer true
bspc config borderless_monocle true
bspc config gapless_monocle true

pgrep -x flameshot >/dev/null || flameshot &

~/.config/polybar/launch.sh &

[ -f ~/.fehbg ] && ~/.fehbg &
